### ISSUE TITLE
Error message while entering/leaving hidden directory

### ISSUE THREAD

**Issue by SciPhy-Two** [lambdalisue/fern.vim#337]
When opened within any file or directory in my  `~/.config/nvim/` directory, an error message is shown in when I do `fern-action-leave` with nvim folder as parent directory . The error message is as follows;

```
[fern] ERROR: {'throwpoint': 'function <SNR>96__worker[12]..<SNR>95__publish[22]..<SNR>95__invoke_callback[6]..<lambda>911[1]..<SNR>136_sync_restore_cursor[6]..<SNR>136_sync_focus_node, line 12', 'exception': 'failed to find a node []'}
```

This does not cause any problem with the function of fern. Everything works ok except the error message is thrown. Also, this error only shows for first time. Repeating the actions would show the error again.

**Comment by lambdalisue** [comment]
I cannot reproduce. Please create [a minimal vimrc](vim/wiki/Minimal-vimrc) and a minimal step by step procedure to reproduce the situation.

**Comment by SciPhy-Two** [comment]
The link you gave is not working. Anyway I made a backup of all my config and just installed vim-plug and fern. The error is still there. I am using nvim nightly appimage.  I am only using these three files, [1](https://pastebin.com/h3t3i501), [vim-plug](https://pastebin.com/fKTeDyP3) and [fern.vim](https://pastebin.com/DtjMZUVU)

**Comment by lambdalisue** [comment]
I fixed the link. Please make a minimal vimrc and minimal step-by-step procedure to reproduce. I'm saying that again because I could not reproduce your issue.

**Comment by SciPhy-Two** [comment]
Thank you for the quick response. I tried with minimal vimrc and the problem is still there. Here's how to reproduce:

1. Open nvim minimal vimrc like in that link you gave.
  (_ I am using nightly appimage. that maybe one of the reasons but I am not sure_)
2. Source [vim-plug](https://pastebin.com/fKTeDyP3) and [fern.vim](https://pastebin.com/DtjMZUVU) from command-line.
3. open drawer with `<Space>ee`
4. Show hidden folders with `<Space>hi`
5. Enter into, not just open, a hidden folder with  `>`  , example say press `>` on `.config.`.
6. That's it the error message is thrown which can be seen with `:messages`

There's no issue in functionality or any other visible problem. Just a flicker of error message

**Comment by SciPhy-Two** [comment]
Accidentally closed my bad

**Comment by SciPhy-Two** [comment]
The new version of appimage doesn't show the issue so closing.
